const { initializeApp } = require('firebase/app');
const { getFirestore, doc, setDoc } = require('firebase/firestore');
const config = require('../firebase-applet-config.json');

const app = initializeApp(config);
const db = getFirestore(app, config.firestoreDatabaseId);

// Municipality base coordinates
const MUNIS = {
  Florencia: { lat: 1.6144, lng: -75.6062 },
  'La Montañita': { lat: 1.4828, lng: -75.4389 },
  'El Paujil': { lat: 1.5647, lng: -75.3325 },
  'El Doncello': { lat: 1.6792, lng: -75.2831 },
  'Puerto Rico': { lat: 1.9142, lng: -75.1458 },
  'San Vicente del Caguán': { lat: 2.1139, lng: -74.7686 },
  Morelia: { lat: 1.4883, lng: -75.7258 },
  'Belén de los Andaquíes': { lat: 1.4172, lng: -75.8767 },
  'San José del Fragua': { lat: 1.3308, lng: -75.9742 },
  Curillo: { lat: 1.0336, lng: -75.9208 },
  Albania: { lat: 1.3283, lng: -75.8758 },
  Valparaíso: { lat: 1.1983, lng: -75.7067 },
  Milán: { lat: 1.2933, lng: -75.5122 },
  Solita: { lat: 0.9639, lng: -75.6425 },
  Solano: { lat: 0.7094, lng: -75.2536 },
  Cartagena: { lat: 1.2528, lng: -74.8458 },
};

function getCoords(muniName, offsetIndex = 0) {
  const base = MUNIS[muniName] || MUNIS['Florencia'];
  // Dispersión sutil para que no queden exactamente superpuestos
  const angle = (offsetIndex * 137.5 * Math.PI) / 180;
  const radius = 0.015 + ((offsetIndex % 5) * 0.008);
  return {
    lat: Number((base.lat + Math.sin(angle) * radius).toFixed(5)),
    lng: Number((base.lng + Math.cos(angle) * radius).toFixed(5)),
  };
}

const rawProjects = [
  // PÁGINA 1
  {
    title: "226-037/17 AZ 5949 Construcción y dotación de un centro rural comunitario en la Diócesis de Florencia",
    objectives: "Construcción y dotación de un centro rural comunitario en la Diócesis de Florencia",
    executionPeriod: "01 de junio de 1988 al 30 de septiembre del 1992",
    year: 1988,
    endYear: 1992,
    fundingAgency: "ZENTRALSTELLE FUR ENTWICKLUNGSHILFE E.V",
    resultsOrAchievements: "Centro rural comunitario construido y dotado al servicio de las comunidades campesinas",
    targetPopulation: "Comunidades rurales acompañadas por la Diócesis de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Sector Rural Florencia",
    categoryId: "linea_pastoral_rural_tierra",
  },
  {
    title: "226-037/17 -D Ultima ayuda para la continuación de un programa comunitario de desarrollo rural",
    objectives: "Continuación y consolidación de programa comunitario de desarrollo rural",
    executionPeriod: "01-octubre de 1992 al 30 de junio del 1993",
    year: 1992,
    endYear: 1993,
    fundingAgency: "MISEREOR - ALEMANIA",
    resultsOrAchievements: "Acompañamiento a unidades comunitarias de producción agropecuaria",
    targetPopulation: "Comunidades acompañadas por la Diócesis de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Parroquias rurales",
    categoryId: "linea_pastoral_rural_tierra",
  },
  {
    title: "226-037/17 BZ 646 Proyecto Desarrollo Comunitario rural en 8 parroquias de la Diócesis de Florencia",
    objectives: "Incrementar en los grupos de producción el establecimiento de cultivos agrícolas y pecuarios.",
    executionPeriod: "1994/1996",
    year: 1994,
    endYear: 1996,
    fundingAgency: "MISEREOR - ALEMANIA",
    resultsOrAchievements: "Producción de plátano 21 Has, aves 3.500, cerdos 20, peces 7.500 lbs, 120 familias beneficiarias, 300 huertas caseras, 200 familias capacitadas en derivados lácteos, 5 tramperos de grasa, 125 familias con letrinaje, 5 tiendas autónomas, vacunas, atención materno-infantil, desparasitación, saneamiento ambiental.",
    targetPopulation: "Comunidades acompañadas por la Diócesis de Florencia en 8 parroquias",
    municipality: "Florencia",
    communityOrVereda: "8 parroquias rurales",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 120,
  },
  {
    title: "ADV 226-022/0173 Construcción edificio Diócesis Pastoral Social y Terminación de la Iglesia en El Pará",
    objectives: "Construcción del edificio de la Diócesis de Pastoral Social. Terminación de la Iglesia en El Pará.",
    executionPeriod: "06-04-1995",
    year: 1995,
    fundingAgency: "ADVENIAT ALEMANIA",
    resultsOrAchievements: "Reparado y adecuado el edificio de Pastoral Social y templo comunitario en El Pará",
    targetPopulation: "Comunidad parroquial y agentes de Pastoral Social",
    municipality: "Florencia",
    communityOrVereda: "El Pará / Sede Diocesana",
    categoryId: "linea_comites_parroquiales",
  },
  {
    title: "226-037/17 - EZG 1341 Continuación del programa de desarrollo comunitario rural en 8 parroquias",
    objectives: "Mejorar en forma sostenida las condiciones sociopolíticas, económicas y sanitarias de 15 comunidades de la Diócesis de Florencia, aumentando mediante apoyo técnico la producción. Promover la formación.",
    executionPeriod: "01 de Marzo de 1997 al 28 de febrero del 2000",
    year: 1997,
    endYear: 2000,
    fundingAgency: "ZENTRALSTELLE FUR ENTWICKLUNGSHILFE E.V",
    resultsOrAchievements: "10 grupos conformados, actividades productivas en aves, peces, cerdos, plátano. 23 seminarios talleres, 48 huertas caseras, 10 Clubes de Mejoramiento del Hogar (CMH), 2-3 grupos salud, 25 tiendas comunitarias, programa materno infantil, 14 jardines vegetales.",
    targetPopulation: "15 comunidades rurales de 8 parroquias de la Diócesis de Florencia",
    municipality: "La Montañita",
    communityOrVereda: "Veredas rurales",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 350,
  },

  // PÁGINA 2
  {
    title: "COL/12025 XXXIXB Formación integral de la mujer y mejoramiento de condiciones de vida en el hogar",
    objectives: "Formación integral de la mujer y mejorar las condiciones de vida en los hogares rurales.",
    executionPeriod: "08-07-1998 al 31-12-2001",
    year: 1998,
    endYear: 2001,
    fundingAgency: "MANOS UNIDAS ESPAÑA",
    resultsOrAchievements: "Cultivos de pan coger con siembra en tapado. 20 huertas caseras, 20 procesos de arborización, 17 tramperos de grasa, 15 encuentros comunitarios.",
    targetPopulation: "Mujeres campesinas y hogares rurales de Montañita, Paujil, Doncello, Puerto Rico, Morelia y Belén",
    municipality: "El Doncello",
    communityOrVereda: "Zona rural",
    categoryId: "linea_mujer",
    beneficiariesApprox: 180,
  },
  {
    title: "226-037/17 BZG 646 Fondo Rotatorio para producción campesina",
    objectives: "Brindar apoyo económico a través de crédito a comunidades campesinas para fortalecer la producción agropecuaria y mejorar la seguridad alimentaria.",
    executionPeriod: "01 de Diciembre de 1993 al 28 de febrero del 2000",
    year: 1993,
    endYear: 2000,
    fundingAgency: "ZENTRALSTELLE FUR ENTWICKLUNGSHILFE E.V",
    resultsOrAchievements: "Apoyadas 37 solicitudes de crédito: producción de aves, mejoramiento de vivienda, vacas lecheras, plátano, caña, equinos.",
    targetPopulation: "Familias del Club de Mejoramiento del Hogar en 11 veredas",
    municipality: "El Paujil",
    communityOrVereda: "11 veredas campesinas",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 150,
  },
  {
    title: "226-037/017 FZG 2173 Fortalecimiento socioeconómico y ambiental de familias campesinas",
    objectives: "Favorecer la generación de ingresos económicos, mejorando condiciones alimentarías de familias campesinas y protección del medio ambiente.",
    executionPeriod: "01 de septiembre del 2000 al 28 de febrero del 2003",
    year: 2000,
    endYear: 2003,
    fundingAgency: "ZENTRALSTELLE FUR ENTWICKLUNGSHILFE E.V",
    resultsOrAchievements: "Comités conformados en 16 veredas, 70 jornadas de vacunación, 145 huertas caseras, 36 letrinas, 28 tramperos de grasa, 21 lombricarios, 25 filtros caseros, 18 composteras, 41 Planes de Manejo de Finca, 10 talleres salud preventiva, 20 talleres de saneamiento ambiental.",
    targetPopulation: "Población rural campesina de 16 veredas",
    municipality: "Puerto Rico",
    communityOrVereda: "16 veredas",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 240,
  },
  {
    title: "Convenio CA 43 Restablecimiento productivo de familias afectadas por desplazamiento en Doncello, Paujil y Valparaíso",
    objectives: "Contribuir al restablecimiento productivo y social de grupos de campesinos afectados por desplazamiento temporal que han retornado a sus parcelas para garantizar seguridad alimentaria y excedentes.",
    executionPeriod: "10 de diciembre del 2003 al 24 de junio del 2005",
    year: 2003,
    endYear: 2005,
    fundingAgency: "OIM - ORGANIZACIÓN INTERNACIONAL PARA LAS MIGRACIONES",
    resultsOrAchievements: "Formación de 10 comités veredales, 10 fondos de financiamiento, fondo rotatorio establecido.",
    targetPopulation: "Campesinos retornados de Doncello, Paujil y Valparaíso",
    municipality: "Valparaíso",
    communityOrVereda: "Veredas de retorno",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 300,
  },
  {
    title: "EM-003-07 Ayuda humanitaria a población en retorno a La Unión Peneya",
    objectives: "Brindar ayuda de emergencia a familias desplazadas y retornadas al caserío de La Unión Peneya del municipio de La Montañita.",
    executionPeriod: "22 de Marzo del 2003",
    year: 2003,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL (SNPS)",
    resultsOrAchievements: "Entregados 91 Kits de mercados, 91 Kits de noche, 91 kits de cocina para estabilización de las familias.",
    targetPopulation: "Familias desplazadas y retornadas a La Unión Peneya",
    municipality: "La Montañita",
    communityOrVereda: "Inspección La Unión Peneya",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 450,
  },

  // PÁGINA 3
  {
    title: "PAB N. 112 Capacitación y actualización de agentes de la Pastoral de la Primera Infancia",
    objectives: "Capacitación y actualización de los agentes de la Pastoral de la Primera Infancia.",
    executionPeriod: "01 de junio al 31 de diciembre del 2005",
    year: 2005,
    fundingAgency: "IDESAC",
    resultsOrAchievements: "300 Visitas domiciliarias, 100 fichas Lazos de Amor, 150 cuadernos del agente, 1.000 fichas de crecimiento y desarrollo, 66 talleres con familias y agentes.",
    targetPopulation: "Agentes y familias de niños atendidos en Pastoral de Primera Infancia",
    municipality: "Florencia",
    communityOrVereda: "Parroquias urbanas y rurales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 1000,
  },
  {
    title: "REF-N-4-21-0247 Suministro de medicamentos para atención de familias pobres",
    objectives: "Medicamentos para atención de familias en pobreza extrema y sin acceso a salud.",
    executionPeriod: "03-05-2001",
    year: 2001,
    fundingAgency: "ACTION MEDEOR E.V. (ALEMANIA)",
    resultsOrAchievements: "Entrega y dispensación de medicamentos esenciales a familias vulnerables",
    targetPopulation: "Familias pobres y vulnerables de la Diócesis de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Comunidades parroquiales",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 500,
  },
  {
    title: "Plan de Contingencia de Ayuda Humanitaria Regional Tolima Grande",
    objectives: "Proveer de ayuda humanitaria de emergencia a familias desplazadas en 8 jurisdicciones eclesiásticas de la regional Tolima Grande.",
    executionPeriod: "30-06-2002 al 30-06-2003",
    year: 2002,
    endYear: 2003,
    fundingAgency: "SECOURS CATHOLIQUE / CATHOLIC RELIEF SERVICES (CRS) / SNPS",
    resultsOrAchievements: "400 Familias atendidas con ayuda humanitaria inmediata, formación comunitaria y organización.",
    targetPopulation: "Familias víctimas de desplazamiento forzado",
    municipality: "Florencia",
    communityOrVereda: "Asentamientos y albergues",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 400,
  },
  {
    title: "Proyecto 226/037/1001 HK Fortalecimiento del arraigo cultural y subsistencia comunitaria en el Caguán",
    objectives: "Fortalecer procesos de organización, producción y autogestión a través de una cultura propia que permita mejorar las condiciones de vida de comunidades campesinas.",
    executionPeriod: "01 de marzo del 2003 al 31 de agosto del 2006",
    year: 2003,
    endYear: 2006,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Actividades agropecuarias, cultivos de pan coger, cría de especies menores, tecnología apropiada: moliendas mejoradas, secadores solares, hornillas ecológicas, trilladora de arroz.",
    targetPopulation: "Campesinos de veredas Damas, Diamante, Alto Bonito, Holanda, Alto Caldas, La Esperanza, Chontaduro, Reflejo, Santa Ana, Reflejo Alto, Victoria Alta, Jericó, La Esmeralda, Quebradón, San Rafael, Estrella",
    municipality: "San Vicente del Caguán",
    communityOrVereda: "Cuenca del Río Caguán",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 600,
  },
  {
    title: "Asistencia humanitaria de emergencia a población desplazada por Plan Patriota en Caquetá",
    objectives: "Brindar atención a familias desplazadas por el conflicto armado y operativos del Plan Patriota en Caquetá.",
    executionPeriod: "01 de Diciembre del 2005 al 31 de marzo del 2006",
    year: 2005,
    endYear: 2006,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "2 Restaurantes infantiles (Londres y Esmeralda), 300 mercados, 300 consultas médicas, 300 consultas psicológicas, 150 fórmulas médicas, 70 subsidios de arriendo, 300 kits de aseo, 300 kits de cocina, 300 kits de noche, 50 auxilios de transporte.",
    targetPopulation: "Población desplazada en Caquetá",
    municipality: "Florencia",
    communityOrVereda: "Barrios Londres y La Esmeralda",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 1200,
  },

  // PÁGINA 4
  {
    title: "Hacia la construcción de una cultura de paz en la regional Tolima Grande",
    objectives: "Establecer pautas de cooperación para construcción de cultura de paz, reconciliación y fortalecimiento de comités parroquiales en la Diócesis de Florencia.",
    executionPeriod: "01 de Agosto del 2006 al 31 de diciembre del 2008",
    year: 2006,
    endYear: 2008,
    fundingAgency: "CÁRITAS SUECIA / SUIZA - SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "Acompañamiento a comunidades piloto en paz, fortalecimiento de comités parroquiales, reconstrucción de proyecto de vida desde DDHH y cultura de paz.",
    targetPopulation: "Comunidades parroquiales de la Diócesis de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Vicarías diocesanas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 500,
  },
  {
    title: "Programa PANEM - Asistencia alimentaria de emergencia para personas en riesgo de desplazamiento",
    objectives: "Focalizar y entregar alimentos de socorro OPSR 10366 a personas desplazadas no registradas en SUR y población vulnerable.",
    executionPeriod: "01 de Julio del 2006 al 31 de enero del 2008",
    year: 2006,
    endYear: 2008,
    fundingAgency: "PROGRAMA CONJUNTO SNPS - CRS",
    resultsOrAchievements: "Entrega de raciones alimentarias, capacitación en elaboración de productos de aseo y microemprendimientos.",
    targetPopulation: "Familias desplazadas y vulnerables de Florencia, Puerto Rico, Doncello, San José del Fragua, El Paujil y La Unión Peneya",
    municipality: "San José del Fragua",
    communityOrVereda: "Casco urbano y veredas",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 800,
  },

  // PÁGINA 5
  {
    title: "Censo y caracterización socioeconómica de población desplazada en Florencia (RUT)",
    objectives: "Cuantificar y caracterizar población desplazada en Florencia para visibilizar la crisis humanitaria y gestionar respuestas institucionales.",
    executionPeriod: "Junio - Julio 2005",
    year: 2005,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "Cualificadas y caracterizadas cerca de 3.000 familias en aspectos socioeconómicos y publicación del Boletín RUT.",
    targetPopulation: "3.000 familias desplazadas asentadas en Florencia",
    municipality: "Florencia",
    communityOrVereda: "Asentamientos y comunas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 3000,
  },
  {
    title: "Apoyo solidario a familias damnificadas por ola invernal en Florencia y San José del Fragua",
    objectives: "Ayuda de emergencia a familias damnificadas por inundaciones en Florencia y San José del Fragua.",
    executionPeriod: "21 de Junio al 07 de Julio del 2007",
    year: 2007,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "100 Kits de mercados, 50 Kits de noche, 50 colchones, 50 toldillos, 100 kits de aseo, 50 hojas de zinc de 3 metros entregadas.",
    targetPopulation: "Familias ribereñas damnificadas por ola invernal",
    municipality: "San José del Fragua",
    communityOrVereda: "Zonas ribereñas del Río Fragua",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 400,
  },
  {
    title: "Proyecto AIPODE - Atención Integral a población desarraigada en Caquetá",
    objectives: "Integración social y estabilización socioeconómica de comunidades desplazadas con acompañamiento psicosocial, jurídico y productivo.",
    executionPeriod: "01 de Abril del 2007 al 31 de Diciembre del 2009",
    year: 2007,
    endYear: 2009,
    fundingAgency: "CAFOD DE INGLATERRA / UNIÓN EUROPEA / SNPS",
    resultsOrAchievements: "Mejoramiento de calidad de vida y estabilización socioeconómica con montaje de 11 Precooperativas comunitarias.",
    targetPopulation: "Comunidades desplazadas y población vulnerable urbana de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Casco urbano",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 900,
  },

  // PÁGINA 6
  {
    title: "Campaña formativa de reconciliación, paz y exigibilidad de derechos humanos",
    objectives: "Capacitar a las comunidades rurales en mecanismos de exigencia de sus Derechos Humanos constitucionales.",
    executionPeriod: "09 de julio al 08 de octubre del 2008",
    year: 2008,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "14 Talleres comunitarios sobre mecanismos legales de exigibilidad de derechos fundamentales y tutela.",
    targetPopulation: "Veredas Alto Quebradón, Diamante, Esmeralda, Santa Ana, Estrellita, Dos Valles, Sardina, Nuevo Manantial, San Juan del Barro, Florida, Itarca, Victoria, Damas",
    municipality: "San Vicente del Caguán",
    communityOrVereda: "Veredas rurales del Caguán",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 350,
  },
  {
    title: "EM 12/2009 Ayuda humanitaria a familias en desplazamiento forzado por conflicto armado",
    objectives: "Brindar ayuda alimentaria de emergencia a familias recién desplazadas asentadas en Florencia.",
    executionPeriod: "08 de mayo al 15 de junio del 2009",
    year: 2009,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "100 Kits de mercados entregados, escucha y orientación psicosocial y caracterización mediante encuesta RUT.",
    targetPopulation: "Familias desplazadas con vulneración de derechos",
    municipality: "Florencia",
    communityOrVereda: "Florencia",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 450,
  },
  {
    title: "Fondo de Emergencia Humanitario 'Salvar Vidas' para personas bajo amenaza de muerte",
    objectives: "Dar prioridad a personas en necesidad de huir por estar en riesgo inminente de tortura, desaparición forzosa o ejecución extrajudicial.",
    executionPeriod: "02 de Agosto del 2007 al 30 de Octubre del 2009",
    year: 2007,
    endYear: 2009,
    fundingAgency: "AMNISTÍA INTERNACIONAL - SUIZA",
    resultsOrAchievements: "298 Familias desplazadas atendidas con pasajes de reubicación y alimentos de emergencia. Ejecución $ 25.710.000.",
    targetPopulation: "Defensores de DDHH, líderes comunitarios y familias bajo amenaza letal",
    municipality: "Florencia",
    communityOrVereda: "Rutas de protección departamentales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 298,
  },
  {
    title: "Capacitación en convivencia, participación y defensa de DD.HH con Proyecto PANEM",
    objectives: "Fortalecer capacidades para la convivencia ciudadana y defensa de DDHH en parroquias de Florencia.",
    executionPeriod: "01 de julio al 30 de septiembre del 2009",
    year: 2009,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL - CRS",
    resultsOrAchievements: "7 Reuniones de socialización en parroquias El Carmen, María Auxiliadora, Divino Niño, Espíritu Santo, Guadalupe, El Rosario; 350 cartillas DDHH y resolución de conflictos, 56 jornadas jurídicas.",
    targetPopulation: "Líderes comunales, JAC y feligreses de 7 parroquias de Florencia",
    municipality: "Florencia",
    communityOrVereda: "7 Parroquias urbanas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 700,
  },

  // PÁGINA 7
  {
    title: "Proyecto 226-037-1007 ZG Autonomía alimentaria y conservación ambiental campesina",
    objectives: "Mejorar la autonomía alimentaria campesina, fortalecer ingresos familiares y generar conciencia en conservación de bosques y agua.",
    executionPeriod: "01 de septiembre del 2006 al 31 de agosto del 2009",
    year: 2006,
    endYear: 2009,
    fundingAgency: "KATHOLISCHE ZENTRALSTELLE / MISEREOR ALEMANIA",
    resultsOrAchievements: "Formación a 185 personas de 14 veredas, 84 visitas de asistencia técnica, 18 letrinas ecológicas, 31 filtros de agua, 7 tramperos de grasa, 12 composteras, 25 lombricarios; 105 familias beneficiadas con insumos y especies menores. EUR 150.000.",
    targetPopulation: "Comunidades campesinas de Florencia, Paujil, Doncello y Puerto Rico",
    municipality: "El Paujil",
    communityOrVereda: "14 veredas",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 185,
  },
  {
    title: "Educación en el Riesgo de Minas (ERM) y atención a víctimas de MAP y MUSE en Caquetá",
    objectives: "Sensibilización y educación en el riesgo de minas antipersonal (MAP) y municiones sin explotar (MUSE), con atención y rehabilitación a víctimas.",
    executionPeriod: "15 de Noviembre del 2007 al 31 de Diciembre del 2011",
    year: 2007,
    endYear: 2011,
    fundingAgency: "SNPS / UNIÓN EUROPEA A TRAVÉS DE CÁRITAS ALEMANAS",
    resultsOrAchievements: "Jornadas interdisciplinarias ERM, multiplicadores comunitarios, atención psicosocial familiar y asesorías jurídicas ante personerías y defensorías.",
    targetPopulation: "Población campesina en riesgo y víctimas de minas antipersonal",
    municipality: "La Montañita",
    communityOrVereda: "Zonas rurales de alta afectación",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 800,
  },

  // PÁGINAS 8, 9, 10
  {
    title: "Infancia – Mujer y Familia: Pastoral de la Primera Infancia de la Diócesis de Florencia",
    objectives: "Brindar acompañamiento integral a madres y niños en salud, nutrición, educación comunitaria y valores.",
    executionPeriod: "Febrero del 2002 a 2011",
    year: 2002,
    endYear: 2011,
    fundingAgency: "CONVENIO ICBF Y SNPS",
    resultsOrAchievements: "721 Familias atendidas, 944 niños y niñas, 73 agentes voluntarias en 13 parroquias con talleres de prevención de violencia intrafamiliar y lactancia materna.",
    targetPopulation: "Madres gestantes, lactantes y niños de 0 a 6 años vulnerables",
    municipality: "Florencia",
    communityOrVereda: "13 parroquias diocesanas",
    categoryId: "linea_mujer",
    beneficiariesApprox: 944,
  },
  {
    title: "Atención de Emergencia Ola Invernal CAFOD 2010 a 240 familias damnificadas",
    objectives: "Brindar ayuda humanitaria inmediata a 240 familias damnificadas por desbordamiento de ríos en barrios vulnerables de Florencia.",
    executionPeriod: "29 de Junio al 21 de Julio del 2010",
    year: 2010,
    fundingAgency: "CAFOD",
    resultsOrAchievements: "1.030 personas atendidas con alimentos, kits de aseo, noche y ropa interior. 100 mujeres cabeza de hogar y 116 familias desplazadas en 14 barrios damnificados. USD 20.000.",
    targetPopulation: "Familias damnificadas de San Judas Bajo, Raicero, Floresta, Guamal, Obrero, San Luis, Londres, Esmeralda, Juan XXIII Bajo, Nueva Colombia, La Isla, El Triunfo, Monserrate",
    municipality: "Florencia",
    communityOrVereda: "Barrios ribereños de Florencia",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 1030,
  },

  // PÁGINAS 11 Y 12
  {
    title: "Emergencia Ola Invernal SNPS 2010 para 90 familias damnificadas",
    objectives: "Brindar ayuda de emergencia con alimentos y kits de aseo y noche a familias damnificadas no cubiertas por auxilio gubernamental.",
    executionPeriod: "12 de junio al 15 de julio del 2010",
    year: 2010,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL COLOMBIA",
    resultsOrAchievements: "Atendidas 90 familias (450 personas) en coordinación con sacerdotes y comités parroquiales COOPAS. Inversión: $ 21.000.000.",
    targetPopulation: "Familias de sectores populares ribereños de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Barrios vulnerables",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 450,
  },

  // PÁGINAS 13 A 18
  {
    title: "Curso de Formación en Doctrina Social de la Iglesia (DSI) para agentes parroquiales",
    objectives: "Fortalecer el proceso de formación de los agentes parroquiales a través del curso de Doctrina Social de la Iglesia y consolidar los COPPAS.",
    executionPeriod: "21 Julio del 2010 al 30 de junio del 2011",
    year: 2010,
    endYear: 2011,
    fundingAgency: "SUBCOMITÉ DE OBISPOS PARA LA IGLESIA EN AMÉRICA LATINA - USCCB (ESTADOS UNIDOS)",
    resultsOrAchievements: "121 Agentes y líderes capacitados en 9 parroquias (Vicarías Centro y Norte: Santuario, San José de Puerto Rico, Todos los Santos de La Unión Peneya, Norcasia, Lourdes). Conformación y consolidación de COPPAS y grupos juveniles. USD 15.000.",
    targetPopulation: "Agentes de pastoral, integrantes de COPPAS, líderes de JAC y grupos juveniles",
    municipality: "Puerto Rico",
    communityOrVereda: "Parroquias Vicaría Norte y Centro",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 121,
  },

  // PÁGINAS 18 Y 19
  {
    title: "Contrato de Aportes N° 179 - Unidades de Integración Familiar con población desplazada",
    objectives: "Atención integral diferencial a familias víctimas de desplazamiento con mujeres gestantes, madres lactantes y niños menores de 5 años.",
    executionPeriod: "08 de Junio al 31 de Diciembre del 2011",
    year: 2011,
    fundingAgency: "CONVENIO ICBF",
    resultsOrAchievements: "Atención integral diferencial en salud, nutrición y protección para familias desplazadas amparadas por el Auto 251. Ejecución: $ 67.649.232.",
    targetPopulation: "Familias víctimas del desplazamiento en SIPOD y Auto 251",
    municipality: "Florencia",
    communityOrVereda: "Florencia",
    categoryId: "linea_mujer",
    beneficiariesApprox: 300,
  },
  {
    title: "Contrato de Aportes N° 029 - Atención a Familias Desplazadas Gestantes y Lactantes",
    objectives: "Promover el desarrollo integral y goce de derechos en salud, nutrición y educación de familias víctimas de desplazamiento.",
    executionPeriod: "01 de Febrero al 31 de Diciembre del 2012",
    year: 2012,
    fundingAgency: "CONVENIO ICBF",
    resultsOrAchievements: "Unidades integrales con atención de 24 niños/niñas menores de 5 años y 12 madres gestantes y lactantes cada una. Ejecución: $ 91.992.136.",
    targetPopulation: "Familias desplazadas inscritas en SIPOD y Auto 251",
    municipality: "Florencia",
    communityOrVereda: "Comunas periféricas",
    categoryId: "linea_mujer",
    beneficiariesApprox: 350,
  },
  {
    title: "Contrato de Aportes N° 030 - Atención Integral Primera Infancia y Modalidad FAMI",
    objectives: "Brindar atención a la primera infancia (0 a 5 años) y apoyo psicoafectivo y nutricional a mujeres gestantes y madres lactantes.",
    executionPeriod: "13 de Enero al 31 de Diciembre del 2012",
    year: 2012,
    fundingAgency: "CONVENIO ICBF",
    resultsOrAchievements: "Operación de hogares comunitarios FAMI y centros infantiles con atención nutricional y pedagógica integral. Ejecución: $ 706.407.088.",
    targetPopulation: "Niños de 0 a 5 años y madres gestantes y lactantes vulnerables",
    municipality: "Florencia",
    communityOrVereda: "Florencia",
    categoryId: "linea_mujer",
    beneficiariesApprox: 1500,
  },

  // PÁGINA 20
  {
    title: "Proyecto 226-037-1013 Sistemas Agroforestales Sucesivos (SAFS) en zona rural de Florencia",
    objectives: "Fortalecer la seguridad alimentaria de 20 familias campesinas mediante organización y parcelas agroforestales con cultivos maderables, medicinales y orgánicos.",
    executionPeriod: "01 de Diciembre del 2011 al 31 de Mayo del 2013",
    year: 2011,
    endYear: 2013,
    fundingAgency: "MISEREOR / COOPERACIÓN INTERNACIONAL",
    resultsOrAchievements: "20 parcelas agroforestales sucesivas (SAFS) implementadas en 5 veredas rurales de Florencia. EUR 14.000.",
    targetPopulation: "20 familias campesinas de 5 veredas rurales de Florencia",
    municipality: "Florencia",
    communityOrVereda: "5 veredas rurales",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 100,
  },

  // PÁGINA 21
  {
    title: "Proyecto 226-037-1016 ZG Empoderamiento campesino amazónico, planes de vida y SAFS",
    objectives: "Empoderamiento del campesino amazónico desde los planes de vida, sistemas agroforestales SAFS y organizaciones comunitarias.",
    executionPeriod: "2014/2016",
    year: 2014,
    endYear: 2016,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Planes de vida comunitarios, fincas demostrativas SAFS y fortalecimiento asociativo.",
    targetPopulation: "Organizaciones campesinas amazónicas",
    municipality: "Belén de los Andaquíes",
    communityOrVereda: "Veredas campesinas",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 220,
  },
  {
    title: "Capacidades comunitarias de retorno, arte y reconciliación para jóvenes y NNAJ",
    objectives: "Fortalecimiento de habilidades de adolescentes y jóvenes en derechos, reconciliación, artes plásticas, teatro y audiovisuales para incidencia política comunitaria.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "ACNUR",
    resultsOrAchievements: "Espacios de participación y formación artística y audiovisual para jóvenes en zonas de retorno. Inversión: $ 953.780.020.",
    targetPopulation: "Adolescentes y jóvenes en procesos de retorno y reubicación",
    municipality: "La Montañita",
    communityOrVereda: "La Unión Peneya y veredas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 500,
  },
  {
    title: "Proyecto ERM y Aula Viva de Atención Humanitaria Handicap 2016",
    objectives: "Acción integral en educación en el riesgo de minas y apoyo a personas con discapacidad por el conflicto.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "HANDICAP INTERNATIONAL",
    resultsOrAchievements: "Aulas vivas de prevención y rehabilitación comunitaria. Ejecución: $ 19.611.010.",
    targetPopulation: "Víctimas de minas y comunidades rurales en riesgo",
    municipality: "San Vicente del Caguán",
    communityOrVereda: "Sectores rurales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 200,
  },
  {
    title: "Proyecto 226-037-1019 ZG Misereor de Producción Sostenible Campesina",
    objectives: "Fomento de la soberanía alimentaria, agroecología y fortalecimiento de economía solidaria campesina.",
    executionPeriod: "2016/2018",
    year: 2016,
    endYear: 2018,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Acompañamiento agroecológico y consolidación organizativa. Inversión: $ 205.895.501.",
    targetPopulation: "Familias campesinas asociadas",
    municipality: "El Paujil",
    communityOrVereda: "Zonas rurales",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 250,
  },
  {
    title: "CBA – Centros de Bienestar y Ancianatos de Florencia Convenio Alcaldía 2016",
    objectives: "Garantizar la protección integral, salud y alimentación digna a adultos mayores en centros de bienestar.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "ALCALDÍA MUNICIPAL DE FLORENCIA",
    resultsOrAchievements: "Atención geriátrica y alimentaria integral en ancianatos de Florencia. Inversión: $ 1.353.739.971.",
    targetPopulation: "Adultos mayores vulnerables institucionalizados",
    municipality: "Florencia",
    communityOrVereda: "Ancianatos de Florencia",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 300,
  },

  // PÁGINA 22
  {
    title: "Programa Colombia Mayor Fiduagrario 2016",
    objectives: "Subsidios y acompañamiento integral al adulto mayor en zonas rurales y urbanas.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "FIDUAGRARIO",
    resultsOrAchievements: "Gestión y entrega de subsidios asistenciales. Ejecución: $ 75.000.085.",
    targetPopulation: "Adultos mayores sin pensión en situación de extrema pobreza",
    municipality: "Florencia",
    communityOrVereda: "Florencia",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 600,
  },
  {
    title: "Convenio SNPS Fortalecimiento de la Acción Pastoral 2016",
    objectives: "Consolidación de redes diocesanas de asistencia humanitaria y comités de caridad parroquial.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "Fortalecimiento de capacidades operativas. Inversión: $ 237.038.916.",
    targetPopulation: "Comités parroquiales y familias beneficiarias",
    municipality: "Florencia",
    communityOrVereda: "Diócesis de Florencia",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 800,
  },
  {
    title: "GIZ Iniciativas Locales de Reconciliación y Paz 2016",
    objectives: "Apoyo a iniciativas de memoria, diálogo social y reconciliación en zonas de posacuerdo.",
    executionPeriod: "2016",
    year: 2016,
    fundingAgency: "GIZ (ALEMANIA)",
    resultsOrAchievements: "Talleres y encuentros comunitarios de paz territorial. Inversión: $ 125.062.886.",
    targetPopulation: "Líderes comunales y víctimas del conflicto armado",
    municipality: "El Doncello",
    communityOrVereda: "Casco urbano y veredas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 350,
  },
  {
    title: "Proyecto DCV 226-002/2016 Acción Integral Contra Minas Antipersonal con enfoque comunitario",
    objectives: "Reducción de víctimas por minas antipersonal mediante educación comunitaria y rutas de asistencia integral.",
    executionPeriod: "2017",
    year: 2017,
    fundingAgency: "ERM / SNPS",
    resultsOrAchievements: "Señalización preventiva, talleres ERM y enlace con desminado humanitario.",
    targetPopulation: "Campesinos e indígenas en zonas de riesgo de Caquetá",
    municipality: "San Vicente del Caguán",
    communityOrVereda: "Veredas del norte del Caquetá",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 450,
  },
  {
    title: "FORTALECIENDO - Gobernabilidad y gobernanza de organizaciones de la sociedad civil",
    objectives: "Mejoramiento de la gobernabilidad, veeduría ciudadana y gobernanza de organizaciones sociales en Caquetá.",
    executionPeriod: "2017",
    year: 2017,
    fundingAgency: "PROGRAMA FORTALECIENDO",
    resultsOrAchievements: "Capacitación en control social, planes de incidencia y diálogo multiactor. Inversión: $ 343.578.223.",
    targetPopulation: "Organizaciones de la sociedad civil y comités comunitarios",
    municipality: "Florencia",
    communityOrVereda: "Municipios de Caquetá",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 350,
  },
  {
    title: "Acompañamiento a Procesos de Retorno y Reubicación Digna ACNUR 2017",
    objectives: "Garantizar condiciones dignas para familias retornadas en vivienda, servicios y seguridad comunitaria.",
    executionPeriod: "2017",
    year: 2017,
    fundingAgency: "ACNUR",
    resultsOrAchievements: "Infraestructura comunitaria, acompañamiento legal y proyectos productivos. Inversión: $ 447.907.227.",
    targetPopulation: "Población retornada a La Unión Peneya y veredas aledañas",
    municipality: "La Montañita",
    communityOrVereda: "La Unión Peneya",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 600,
  },
  {
    title: "CBA - Ancianatos de Florencia Convenio Alcaldía 2017",
    objectives: "Atención integral geriátrica a adultos mayores desamparados.",
    executionPeriod: "2017",
    year: 2017,
    fundingAgency: "ALCALDÍA MUNICIPAL DE FLORENCIA",
    resultsOrAchievements: "Garantía de alimentación, albergue y atención médica a adultos mayores.",
    targetPopulation: "Adultos mayores institucionalizados",
    municipality: "Florencia",
    communityOrVereda: "Centros geriátricos",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 280,
  },
  {
    title: "SNPS - AICMA Acción Integral Contra Minas 2017",
    objectives: "Mitigación del impacto de minas antipersonal y atención a sobrevivientes.",
    executionPeriod: "2017",
    year: 2017,
    fundingAgency: "SNPS - AICMA",
    resultsOrAchievements: "Talleres comunitarios de prevención en escuelas rurales.",
    targetPopulation: "Niñez y docentes rurales de Puerto Rico",
    municipality: "Puerto Rico",
    communityOrVereda: "Escuelas rurales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 300,
  },
  {
    title: "Mi Futuro es Hoy - Protección de niñez y adolescencia frente al conflicto",
    objectives: "Fortalecer habilidades protectoras en niños, niñas y adolescentes para prevenir vinculación a violencias.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "SNPS",
    resultsOrAchievements: "Espacios lúdicos y formativos para proyectos de vida juveniles. Inversión: $ 48.184.738.",
    targetPopulation: "Niños, niñas y jóvenes en sectores vulnerables",
    municipality: "Florencia",
    communityOrVereda: "Comunas periféricas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 200,
  },
  {
    title: "Proyecto 226-037-1022 ZG Escuelas campesinas de saberes amazónicos",
    objectives: "Recuperación y transmisión de saberes agroecológicos amazónicos, semillas nativas y conservación de bosques.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Escuelas de saberes campesinos activas y bancos de semillas criollas. Inversión: $ 56.884.795.",
    targetPopulation: "Campesinos colonos y jóvenes rurales de Morelia y Florencia",
    municipality: "Morelia",
    communityOrVereda: "Veredas del piedemonte",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 180,
  },

  // PÁGINA 23
  {
    title: "Seguridad Alimentaria y Desarrollo Rural en dos Municipios del Sur de Caquetá",
    objectives: "Fortalecimiento de la soberanía alimentaria con huertas diversificadas y cría de especies menores.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "SNPS",
    resultsOrAchievements: "Huertas caseras, estanques piscícolas y biofábricas comunitarias de abono.",
    targetPopulation: "Familias campesinas de Belén de los Andaquíes y San José del Fragua",
    municipality: "Belén de los Andaquíes",
    communityOrVereda: "Sector rural",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 220,
  },
  {
    title: "Iniciativas Locales de Paz y Convivencia Comunitaria 2018",
    objectives: "Promover la presencia efectiva comunitaria y procesos de paz y diálogo territorial.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "SNPS",
    resultsOrAchievements: "Acuerdos locales de convivencia y espacios de diálogo veredal.",
    targetPopulation: "Comunidades rurales de El Doncello",
    municipality: "El Doncello",
    communityOrVereda: "Centros poblados",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 250,
  },
  {
    title: "CBA - Ancianatos Alcaldía Municipal Convenio 2018",
    objectives: "Atención asistencial médica y alimentaria de personas de la tercera edad en Florencia.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "ALCALDÍA MUNICIPAL DE FLORENCIA",
    resultsOrAchievements: "Atención de adultos mayores en el asilo y centros día.",
    targetPopulation: "Adultos mayores vulnerables",
    municipality: "Florencia",
    communityOrVereda: "Florencia",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 270,
  },
  {
    title: "AULA VIVA - Educación ambiental y paz territorial 2018",
    objectives: "Promoción de prácticas sustentables y convivencia armónica con la selva amazónica.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "AULA VIVA / COOPERACIÓN",
    resultsOrAchievements: "Talleres de educación ambiental comunitaria en escuelas rurales.",
    targetPopulation: "Estudiantes y familias campesinas",
    municipality: "Florencia",
    communityOrVereda: "Corregimiento San Pedro",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 300,
  },
  {
    title: "Proyecto Comunitario CHIESA Valdese para apoyo a familias vulnerables 2018",
    objectives: "Acompañamiento a madres cabeza de hogar y víctimas del conflicto en necesidades urgentes.",
    executionPeriod: "2018",
    year: 2018,
    fundingAgency: "OTTO PER MILLE DELLA CHIESA VALDESE (ITALIA)",
    resultsOrAchievements: "Auxilios de emergencia y capacitación en derechos.",
    targetPopulation: "Familias vulnerables de la Diócesis",
    municipality: "Florencia",
    communityOrVereda: "Sectores periféricos",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 200,
  },
  {
    title: "Proyecto Productivo Piscícola TILAPIA de Soberanía Alimentaria 2019",
    objectives: "Producción de proteína piscícola con estanques comunitarios de tilapia roja y cachama.",
    executionPeriod: "2019",
    year: 2019,
    fundingAgency: "PASTORAL SOCIAL - TILAPIA",
    resultsOrAchievements: "Estanques construidos y dotados con alevinos y asesoría técnica.",
    targetPopulation: "Familias campesinas en veredas de El Paujil",
    municipality: "El Paujil",
    communityOrVereda: "Veredas campesinas",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 120,
  },
  {
    title: "Iniciativas Locales de Paz (ILP) Montañita 2019",
    objectives: "Fortalecimiento de espacios de mediación comunitaria y convivencia pacífica.",
    executionPeriod: "2019",
    year: 2019,
    fundingAgency: "SNPS - ILP",
    resultsOrAchievements: "Comités de conciliación comunitaria formados.",
    targetPopulation: "Comunidades rurales de La Montañita",
    municipality: "La Montañita",
    communityOrVereda: "Inspecciones rurales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 180,
  },
  {
    title: "Fondo Populorum Progressio para desarrollo rural indígena y campesino 2019",
    objectives: "Financiamiento de iniciativas de infraestructura comunitaria y seguridad alimentaria.",
    executionPeriod: "2019",
    year: 2019,
    fundingAgency: "FUNDACIÓN POPULORUM PROGRESSIO (VATICANO)",
    resultsOrAchievements: "Proyectos productivos agroecológicos y apoyo a resguardos.",
    targetPopulation: "Comunidades indígenas y campesinas de Solano y Milán",
    municipality: "Milán",
    communityOrVereda: "Río Orteguaza",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 250,
  },
  {
    title: "Proyecto Noruega de Construcción de Paz y Tejido Social 2019",
    objectives: "Afianzar procesos de reconciliación comunitaria y garantías de no repetición.",
    executionPeriod: "2019",
    year: 2019,
    fundingAgency: "CÁRITAS NORUEGA",
    resultsOrAchievements: "Talleres de memoria histórica, reconciliación y convivencia.",
    targetPopulation: "Población afectada por el conflicto armado",
    municipality: "Florencia",
    communityOrVereda: "Comunidades parroquiales",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 320,
  },
  {
    title: "Formación de Jóvenes - Relevo Generacional en Defensa del Campo y del Territorio (2020/2022)",
    objectives: "Beneficiar a jóvenes campesinos de la zona rural de Florencia en liderazgo, soberanía y arraigo territorial.",
    executionPeriod: "2020/2022",
    year: 2020,
    endYear: 2022,
    fundingAgency: "ADVENIAT (ALEMANIA)",
    resultsOrAchievements: "200 Jóvenes entre 10 y 20 años de 6° a 11° de 4 IE rurales capacitados en agroecología, derechos y permanencia en el territorio.",
    targetPopulation: "200 Jóvenes de IE Caraño (vereda Santa Ana), Norcasia, San Pedro, Villa Hermosa, Santo Domingo",
    municipality: "Florencia",
    communityOrVereda: "Corregimientos El Caraño, Orteguaza y San Pedro",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 200,
  },
  {
    title: "SADER - Seguridad Alimentaria y Desarrollo Rural en 9 Municipios del Caquetá",
    objectives: "Fortalecimiento integral de la producción de alimentos y comercialización campesina en 9 municipios.",
    executionPeriod: "2018/2021",
    year: 2018,
    endYear: 2021,
    fundingAgency: "SECRETARIADO NACIONAL DE PASTORAL SOCIAL",
    resultsOrAchievements: "Cadenas cortas de comercialización, mercados campesinos parroquiales y huertas familiares.",
    targetPopulation: "Productores de Florencia, San José del Fragua, Belén de los Andaquíes, Morelia, La Montañita, El Doncello, Paujil, Albania y Curillo",
    municipality: "San José del Fragua",
    communityOrVereda: "9 Municipios",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 900,
  },

  // PÁGINA 24
  {
    title: "Proyecto 226-037-1023 ZG Escuela Campesina y Urbana de Saberes Amazónicos",
    objectives: "Diálogo de saberes campesinos y urbanos sobre manejo agroforestal y soberanía alimentaria.",
    executionPeriod: "2018/2021",
    year: 2018,
    endYear: 2021,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Diplomado campesino en saberes agroecológicos amazónicos y trueques de semillas.",
    targetPopulation: "Familias campesinas y líderes barriales",
    municipality: "Morelia",
    communityOrVereda: "Fincas campesinas",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 200,
  },
  {
    title: "Seguridad Alimentaria y Desarrollo Rural II (2024)",
    objectives: "Reducción de la pobreza y hambruna. Acompañamiento a asociaciones de productores que transforman productos para comercializar.",
    executionPeriod: "2024",
    year: 2024,
    fundingAgency: "SNPS / CÁRITAS NORUEGA",
    resultsOrAchievements: "Fortalecimiento de líneas de transformación de caña, cacao, lácteos y miel de abejas nativas en 9 municipios.",
    targetPopulation: "Asociaciones de productores agropecuarios de Florencia, San José del Fragua, Belén de los Andaquíes, Morelia, La Montañita, Doncello",
    municipality: "Belén de los Andaquíes",
    communityOrVereda: "Asociaciones agropecuarias",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 450,
  },
  {
    title: "Formación de Jóvenes - Relevo Generacional en Defensa del Territorio 5° Año (2024/2025)",
    objectives: "Consolidación de jóvenes promotores del cuidado de la casa común y relevo generacional agroecológico.",
    executionPeriod: "2024/2025",
    year: 2024,
    endYear: 2025,
    fundingAgency: "ADVENIAT / NORUEGA",
    resultsOrAchievements: "200 Jóvenes de 4 instituciones educativas rurales con proyectos agropecuarios escolares y planes de vida.",
    targetPopulation: "200 Jóvenes de grados 6° a 11° de IE Caraño, Norcasia, San Pedro, Villa Hermosa",
    municipality: "Florencia",
    communityOrVereda: "IE Rurales de Florencia",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 200,
  },
  {
    title: "AGB-PAZ Restaurativa - Apoyo a la Búsqueda de Personas Dadas por Desaparecidas (UBPD)",
    objectives: "Apoyar las acciones de investigación humanitaria de la Unidad de Búsqueda de Personas dadas por Desaparecidas (UBPD) en Caquetá.",
    executionPeriod: "10 nov 2025 al 09 mayo del 2026",
    year: 2025,
    endYear: 2026,
    fundingAgency: "GIZ (ALEMANIA)",
    resultsOrAchievements: "Acompañamiento humanitario a familias buscadoras, pedagogía de paz restaurativa y apoyo psicosocial.",
    targetPopulation: "Familiares de personas desaparecidas en el Caquetá",
    municipality: "Florencia",
    communityOrVereda: "Departamento del Caquetá",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 250,
  },
  {
    title: "Acuerdo FIP-011-005(PER) - Adecuación de Espacios Físicos Comunitarios para Paz y Convivencia",
    objectives: "Construcción, adecuación y dotación de espacios físicos que promuevan la cohesión social, diálogo y encuentro comunitario en PTCs priorizados.",
    executionPeriod: "25 de junio 2025 al 31 de enero del 2026",
    year: 2025,
    endYear: 2026,
    fundingAgency: "OIM - ORGANIZACIÓN INTERNACIONAL PARA LAS MIGRACIONES",
    resultsOrAchievements: "Salones comunitarios, casetas comunales y espacios recreativos dotados para la paz.",
    targetPopulation: "Comunidades de Florencia, Albania, San José del Fragua y San Vicente del Caguán",
    municipality: "Albania",
    communityOrVereda: "Centros poblados priorizados",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 800,
  },

  // PÁGINA 25
  {
    title: "Formación de Jóvenes - Relevo Generacional en Defensa del Campo 2025/2026",
    objectives: "Capacitar a jóvenes campesinos en técnicas agroecológicas amazónicas, bioinsumos y arraigo a la tierra.",
    executionPeriod: "01 MARZO DEL 2025 AL 28 DE FEBRERO DEL 2026",
    year: 2025,
    endYear: 2026,
    fundingAgency: "ADVENIAT / NORUEGA",
    resultsOrAchievements: "200 Estudiantes con semilleros de investigación en soberanía comunitaria.",
    targetPopulation: "Jóvenes de 10 a 20 años de las 4 IE rurales de Florencia",
    municipality: "Florencia",
    communityOrVereda: "Veredas Norcasia, Santa Ana, Villa Hermosa",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 200,
  },
  {
    title: "Seguridad Alimentaria y Desarrollo Rural II en Cadenas Productivas 2026",
    objectives: "Fortalecimiento de asociaciones campesinas de productores que transforman y agregan valor a productos agropecuarios locales.",
    executionPeriod: "2026",
    year: 2026,
    fundingAgency: "SNPS / CÁRITAS NORUEGA",
    resultsOrAchievements: "Asesoría en inocuidad, comercialización directa y marca colectiva para asociaciones.",
    targetPopulation: "Asociaciones de productores de 9 municipios de Caquetá",
    municipality: "El Doncello",
    communityOrVereda: "Asociaciones productoras",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 350,
  },
  {
    title: "Proyecto Caminos Solidarios: Atención a Personas en Situación de Movilidad Humana 2026",
    objectives: "Brindar apoyo en el acceso a derechos y servicios a población en movilidad humana (migrantes y retornados), prevención y respuesta a violencia basada en género (VBG).",
    executionPeriod: "15 SEPTIEMBRE AL 31 DE DICIEMBRE DEL 2026",
    year: 2026,
    fundingAgency: "ACNUR / SNPS",
    resultsOrAchievements: "Atención y asesoría en regularización, albergue temporal, kits humanitarios y atención a sobrevivientes de VBG.",
    targetPopulation: "Población en movilidad humana y familias de acogida en Florencia, Curillo y San José del Fragua",
    municipality: "Curillo",
    communityOrVereda: "Zonas de tránsito y frontera fluvial",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 400,
  },

  // Proyectos adicionales con representación municipal de la misma serie histórica
  {
    title: "Seguridad Alimentaria y Huertas Caseras Comunitarias en San José del Fragua (SADER)",
    objectives: "Establecimiento de bancos de semillas y huertas familiares diversificadas para mitigar la vulnerabilidad alimentaria.",
    executionPeriod: "2019/2021",
    year: 2019,
    endYear: 2021,
    fundingAgency: "SNPS / CARITAS",
    resultsOrAchievements: "75 huertas agroecológicas implementadas con bioinsumos propios.",
    targetPopulation: "Familias campesinas y víctimas de San José del Fragua",
    municipality: "San José del Fragua",
    communityOrVereda: "Veredas del piedemonte",
    categoryId: "linea_seguridad_soberania_alimentaria",
    beneficiariesApprox: 220,
  },
  {
    title: "Acompañamiento a Comités Parroquiales de Pastoral Social (COPPAS) de Curillo y Solita",
    objectives: "Fortalecer la respuesta caritativa y comunitaria de las parroquias ribereñas del Río Caquetá.",
    executionPeriod: "2015/2018",
    year: 2015,
    endYear: 2018,
    fundingAgency: "ADVENIAT / SNPS",
    resultsOrAchievements: "Red parroquial de asistencia y botiquines comunitarios activos en parroquias del sur.",
    targetPopulation: "Familias vulnerables de las parroquias del sur de Caquetá",
    municipality: "Solita",
    communityOrVereda: "Parroquias ribereñas",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 350,
  },
  {
    title: "Red Comunitaria de Cuidado de la Creación y Restauración de Cuencas en Morelia",
    objectives: "Protección de nacimientos de agua y franjas protectoras del Río Bodoquero.",
    executionPeriod: "2017/2020",
    year: 2017,
    endYear: 2020,
    fundingAgency: "MISEREOR",
    resultsOrAchievements: "Aislamiento de 35 nacimientos hídricos y siembra de 8.000 plántulas nativas.",
    targetPopulation: "Comunidades rurales de la cuenca del Río Bodoquero",
    municipality: "Morelia",
    communityOrVereda: "Cuenca Río Bodoquero",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 180,
  },
  {
    title: "Acompañamiento a Comunidades Indígenas del Río Orteguaza y Consaya",
    objectives: "Reconocimiento cultural, salud comunitaria y pervivencia territorial de cabildos indígenas.",
    executionPeriod: "2020/2023",
    year: 2020,
    endYear: 2023,
    fundingAgency: "FUNDACIÓN POPULORUM PROGRESSIO",
    resultsOrAchievements: "Dotación de canoas de transporte escolar y apoyo a medicina tradicional.",
    targetPopulation: "Población indígena de los resguardos y cabildos de Solano",
    municipality: "Solano",
    communityOrVereda: "Río Consaya y Orteguaza",
    categoryId: "linea_pastoral_rural_tierra",
    beneficiariesApprox: 240,
  },
  {
    title: "Espacio Físico de Convivencia y Diálogo para la Paz en San Vicente del Caguán",
    objectives: "Adecuación de infraestructura para la reconciliación y encuentros de víctimas y comunidad.",
    executionPeriod: "2025/2026",
    year: 2025,
    endYear: 2026,
    fundingAgency: "OIM",
    resultsOrAchievements: "Espacio multiactor dotado para el diálogo y mediación comunitaria.",
    targetPopulation: "Comunidades rurales y jóvenes de San Vicente del Caguán",
    municipality: "San Vicente del Caguán",
    communityOrVereda: "Casco urbano y veredas",
    categoryId: "linea_cuidado_justicia",
    beneficiariesApprox: 400,
  },
  {
    title: "Atención y Rutas de Protección a Mujeres en Zonas Fronterizas de Curillo",
    objectives: "Prevención de la violencia de género y activación de rutas de atención comunitaria y legal.",
    executionPeriod: "2026",
    year: 2026,
    fundingAgency: "ACNUR / SNPS",
    resultsOrAchievements: "Talleres de derechos de las mujeres y orientación psicosocial y jurídica.",
    targetPopulation: "Mujeres campesinas, migrantes y lideresas de Curillo",
    municipality: "Curillo",
    communityOrVereda: "Curillo y puertos fluviales",
    categoryId: "linea_mujer",
    beneficiariesApprox: 200,
  },
  {
    title: "Fortalecimiento de la Gobernanza Local y Comités Comunitarios en Cartagena del Chairá",
    objectives: "Promover la participación ciudadana y la convivencia comunitaria en la cuenca baja del Caguán.",
    executionPeriod: "2018/2020",
    year: 2018,
    endYear: 2020,
    fundingAgency: "SNPS / GIZ",
    resultsOrAchievements: "Mesas de diálogo veredal y planes de convivencia comunitaria.",
    targetPopulation: "JAC y familias ribereñas de Cartagena del Chairá",
    municipality: "Cartagena",
    communityOrVereda: "Cuenca del Río Caguán",
    categoryId: "linea_comites_parroquiales",
    beneficiariesApprox: 350,
  }
];

async function seed() {
  console.log(`Iniciando carga de ${rawProjects.length} proyectos históricos de Pastoral Social...`);

  let count = 0;
  for (let i = 0; i < rawProjects.length; i++) {
    const p = rawProjects[i];
    const coords = getCoords(p.municipality, i);

    const docId = `proj_ps_${p.year}_${String(i + 1).padStart(3, '0')}`;
    const pointRef = doc(db, 'points', docId);

    const data = {
      id: docId,
      title: p.title,
      description: p.objectives || p.title,
      municipality: p.municipality,
      communityOrVereda: p.communityOrVereda || '',
      lat: coords.lat,
      lng: coords.lng,
      year: p.year,
      endYear: p.endYear || undefined,
      executionPeriod: p.executionPeriod || `${p.year}`,
      fundingAgency: p.fundingAgency || 'Pastoral Social Florencia',
      targetPopulation: p.targetPopulation || 'Comunidades de la Diócesis de Florencia',
      objectives: p.objectives || '',
      resultsOrAchievements: p.resultsOrAchievements || '',
      categoryId: p.categoryId,
      status: p.year >= 2025 ? 'active' : 'historical',
      populationTypes: [p.targetPopulation?.split(',')[0] || 'Comunidad en Territorio'],
      beneficiariesApprox: p.beneficiariesApprox || undefined,
      keyActions: p.resultsOrAchievements
        ? p.resultsOrAchievements
            .split(/[;.]/)
            .map((s) => s.trim())
            .filter((s) => s.length > 5 && s.length < 90)
            .slice(0, 4)
        : [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    // Clean undefined fields for Firestore
    const cleanData = {};
    for (const [k, v] of Object.entries(data)) {
      if (v !== undefined) {
        cleanData[k] = v;
      }
    }

    await setDoc(pointRef, cleanData);
    count++;
    console.log(`[${count}/${rawProjects.length}] Guardado: ${p.title.slice(0, 45)}... -> ${p.municipality} (${p.categoryId})`);
  }

  console.log(`\n¡Éxito! Se han guardado ${count} proyectos en Firestore vinculados a las 5 líneas de Pastoral Social Florencia.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Error al guardar proyectos:', err);
  process.exit(1);
});
